pub mod alive_check;
pub mod diagnostic_message;
pub mod entity_status;
pub mod generic_header_nack;
pub mod header;
pub mod payload;
pub mod power_mode_info;
pub mod routing_activation;
pub mod vehicleident;
